# Generated by Django 5.1.1 on 2024-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep2s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_file',
            field=models.FileField(upload_to='topics/'),
        ),
    ]
