# Generated by Django 5.1.1 on 2024-11-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep2s', '0002_alter_topic_content_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
